
package help;

import java.awt.Color;
import java.awt.ComponentOrientation;

import javax.swing.JOptionPane;


/**
 *
 * @author R-Walid Pro_Book
 */
public class Introduction extends javax.swing.JFrame {
    

    /**
     * Creates new form Introduction
     */
    
    private String[] str;
    private int getRandomDuaIndex() {
        return (int) Math.ceil(Math.random() * 25 + 1);
    }

    private void setDuaSource() {
        if (!((db.getDuaSource(getRandomDuaIndex())) == null)) {
            str = db.getDuaSource(getRandomDuaIndex());            
            
            duaArea.setText(str[0]);
            sourcePaper.setText(str[1]);
        }
    }

    public Introduction() {
        try {
            this.setUndecorated(true);
            initComponents();
            this.setBackground(new Color(0.0f, 0.0f, 0.0f, 0.0f));
            duaArea.setLineWrap(true);
            duaArea.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
            sourcePaper.setLineWrap(true);
            sourcePaper.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
            setDuaSource();            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Introduction Constructor : " + ex.getMessage());
            setDuaSource();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        duaArea = new javax.swing.JTextArea();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        sourcePaper = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 0));
        setForeground(new java.awt.Color(255, 0, 204));
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(466, 589));
        setResizable(false);
        setSize(new java.awt.Dimension(883, 400));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        duaArea.setEditable(false);
        duaArea.setBackground(new java.awt.Color(233, 203, 143));
        duaArea.setColumns(20);
        duaArea.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        duaArea.setRows(5);
        duaArea.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane2.setViewportView(duaArea);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(90, 90, 290, 280);

        jTextField2.setBackground(new java.awt.Color(233, 203, 143));
        jTextField2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jTextField2);
        jTextField2.setBounds(80, 80, 310, 0);

        sourcePaper.setEditable(false);
        sourcePaper.setBackground(new java.awt.Color(233, 203, 143));
        sourcePaper.setColumns(20);
        sourcePaper.setFont(new java.awt.Font("Monospaced", 0, 17)); // NOI18N
        sourcePaper.setRows(5);
        sourcePaper.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jScrollPane3.setViewportView(sourcePaper);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(130, 370, 250, 130);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/help/duaPaper.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 520, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            System.out.println("form is Opened");
            Thread.sleep(12000);
            this.setVisible(false);
            this.setDefaultCloseOperation(EXIT_ON_CLOSE);
            new loginWindow().setVisible(true);     
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Introduction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Introduction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Introduction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Introduction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Introduction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea duaArea;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextArea sourcePaper;
    // End of variables declaration//GEN-END:variables
}
